modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "${issue_tracker_url}"
license = "${license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${display_url}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId="geckolib3"
mandatory=true
versionRange="${geckolib_version_range}"
ordering="BEFORE"
side="BOTH"